import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

class CompliancePDFGenerator {
  async generateExportReport(farmData, checklistResults) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers = [];
        
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfData = Buffer.concat(buffers);
          resolve(pdfData.toString('base64'));
        });

        // Add Sian Technologies branding
        doc.fontSize(20).text('SIAN EXPORT-READY REPORT', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Generated: ${new Date().toLocaleDateString()}`, { align: 'center' });
        doc.moveDown(2);

        // Farm Information Section
        doc.fontSize(16).text('1. FARM INFORMATION', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(12).text(`Farm Name: ${farmData.name || 'N/A'}`);
        doc.text(`Farmer: ${farmData.farmerName || 'N/A'}`);
        doc.text(`Location: ${farmData.location || 'N/A'}`);
        doc.text(`GPS Coordinates: ${farmData.coordinates || 'N/A'}`);
        doc.moveDown();

        // Compliance Checklist Section
        doc.fontSize(16).text('2. UK COMPLIANCE CHECKLIST', { underline: true });
        doc.moveDown(0.5);
        
        checklistResults.forEach((item, index) => {
          const status = item.passed ? '✅ PASS' : '❌ FAIL';
          doc.fontSize(12).text(`${index + 1}. ${item.requirement}: ${status}`);
          if (item.notes) {
            doc.fontSize(10).text(`   Note: ${item.notes}`, { indent: 20 });
          }
        });
        doc.moveDown();

        // Geo Verification Section
        doc.fontSize(16).text('3. GEOSPATIAL VERIFICATION', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(12).text(`Verified Location: ${farmData.geoVerified ? '✅ YES' : '❌ NO'}`);
        doc.text(`Verification Date: ${farmData.geoVerifiedDate || 'N/A'}`);
        doc.text(`Satellite Imagery: ${farmData.satelliteImageAvailable ? '✅ Available' : '❌ Not Available'}`);
        doc.moveDown();

        // Final Certification
        doc.moveDown(2);
        doc.fontSize(14).text('CERTIFICATION STATUS', { align: 'center' });
        const overallStatus = checklistResults.every(r => r.passed) ? '✅ EXPORT READY' : '⚠️ ACTION REQUIRED';
        doc.fontSize(16).text(overallStatus, { align: 'center' });
        
        doc.moveDown(4);
        doc.fontSize(10).text('This report was generated by Sian Technologies. It is a preliminary assessment and does not constitute official UK import approval.', { align: 'center', width: 500 });

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }
}

export default new CompliancePDFGenerator();